# -*- coding: utf-8 -*-
"""Lyrics_NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEpHw6tA50k3gjUZQlxHrf7Ytx9fKJcg

## Purpose

The purpose of this notebook is to display a working example of how to use Google's universal sentence encoder to compare two different strings. The general idea is to apply some basic NLP techniques with Spacy in order to increase the weights of the 'important' aspects of a sentence, then apply the sentence encoder to get a vector representation of the sentances. These sentances are later compared.

In general, there will be one news article that is inputted. This will be compared to a dataframe of songs that have already been processed by the encoder. The one with the best cosine similarity will be selected.
"""

import numpy as np
import pandas as pd
from Support_functions import nlp_weighting
from Support_functions import embed

 

#First we import all of the song Lyrics (this should probably be done in another python script)
df_songs = pd.DataFrame(pd.read_csv('songdata.csv'))

#If you want to subset to only select certain artists, this is the place to do so:

#political_artists = ['Zac Brown Band',
#'Ziggy Marley',
#'The Beatles',
#'Arrogant Worms',
#'Billy Joel',
#'Bob Marley',
#'Coldplay',
#'Creedence Clearwater Revival',
#'Elton John',
#'Eminem',
#'Fleetwood Mac',
#'Garth Brooks',
#'John Denver',
#'Kanye West',
#'Linkin Park',
#'Lynyrd Skynyrd',
#'Rage Against The Machine',
#'Rascal Flatts',
#'Red Hot Chili Peppers',
#'System Of A Down',
#'Tragically Hip',
#'The White Stripes']
#df_songs_political = df_songs[df_songs['artist'].isin(political_artists)]

#If subsetting, comment out the following line:
df_songs_political = df_songs

df_songs_political=df_songs_political.dropna(subset=['text'])
df_songs_political['text'] = df_songs_political['text'].apply(lambda x: x.replace('\n',' '))
df_songs_politcal_lyrics= list(df_songs_political.iloc[:,3])

"""## Here we begin to implement some of the NLP
"""

df_songs_politcal_lyrics = nlp_weighting(df_songs_politcal_lyrics)

"""Note below we have the version where we are taking TFIDF Weights. In reality, this would be harder to implement. In practice, we will use a pretrained model that will be able to return a vector to compare similarities. Also, we will want to restrict the size of our data in order to make comparisons feasible.
"""
df_songs_political_lyrics_embed = embed(df_songs_politcal_lyrics)

df_songs_political_lyrics_embed.to_csv('Lyric_embeddings.csv')
